[package]
name = "rust_core"
version = "0.1.0"
edition = "2024"

[dependencies]
flutter_rust_bridge = '2.11.1'
libc = '0.2.174'
embedded-hal = "1.0.0"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "2.11.1"